spring.application.name=RestApiBasic
spring.datasource.url=jdbc:mysql://localhost:3306/crud1
spring.datasource.username=root
spring.datasource.password=7381580

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081